apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-repository-v2
  title: Create Azure Repository V2
  description: Create a new azure repository with more steps and a catalog registration
  tags:
    - recommended
    - cloud-azure
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
        - service
      properties:
        name:
          title: Repository Name
          type: string
          description: The name of the repository
          ui:autofocus: true
          ui:options:
            rows: 5
        service:
          title: Service Name
          type: string
          description: The name of the service
          ui:options:
            rows: 5
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content/create-azure-repository-v2
        values:
          name: ${{ parameters.name }}
          service: ${{ parameters.service }}

    - id: publish-azure
      name: Publish to Azure DevOps
      action: publish:azure
      input:
        allowedHosts: ["dev.azure.com"]
        description: This is ${{ parameters.name }}
        repoUrl: "dev.azure.com?repo=${{ parameters.name }}&organization=luishenrique92250483&project=backstage"
        project: backstage
        organization: luishenrique92250483

    - id: create-branch
      name: Create Branch
      action: azure:create-branch
      input:
        repository: ${{ parameters.name }}
        organization: luishenrique92250483
        project: backstage
        branchNames: ["develop", "qa", "uat"]

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-azure'].output.remoteUrl }}?path=%2F
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish-azure'].output.remoteUrl }}?path=%2F
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
